cart/urls.py
from django.urls import path
from cart import views


app_name = 'cart'

urlpatterns = [
    path('', views.show, name='show'),
    path('add/<uuid:id>', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
]

fleamarket/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from fleamarket import views, settings

urlpatterns = [
    path('', views.index, name='index'),
    path('', include('users.urls')),
    path('product/', include('product.urls')),
    path('category/', include('category.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from payment import views


app_name = 'payment'

urlpatterns = [
    path('purchase/', views.purchase_show, name='purchase_show'),
    path('sale/', views.sale_show, name='sale_show'),
    path('buy/<uuid:id>', views.buy, name='buy'),
    path('close_cart/', views.close_cart, name='close_cart'),
]

product/urls.py
from django.urls import path
from product import views


app_name = 'product'

urlpatterns = [
    path('<uuid:id>/', views.product_by_id, name='product_by_id'),
    path('create/', views.create, name='create'),
    path('edit/<uuid:id>', views.edit, name='edit'),
    path('list/', views.list_by_user, name='list_by_user'),
    path('list_by_name/', views.list_by_name, name='list_by_name'),
    path('delete/', views.delete, name='delete'),
    path('fast_create/', views.fast_create, name='fast_create'),
    path('update_quantity/', views.update_quantity, name='update_quantity'),
    path('create_question/<uuid:id>', views.create_question, name='create_question'),
    path('answer_question/<uuid:id>', views.answer_question, name='answer_question'),
]

cart/models.py
from product.models import Product
import uuid
from django.db import models
from django.db.models.deletion import CASCADE
from users.models import User


class Cart(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    owner = models.OneToOneField(User, on_delete=CASCADE)
    products = models.ManyToManyField(Product)

    def __str__(self):
        return self.owner.username

cart/views.py
from django.http.response import JsonResponse
from product.models import Product
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from product.models import Product
from category.models import Category
from cart.models import Cart


@login_required
def show(request):
    categories = Category.objects.all()
    cart = Cart.objects.get(owner=request.user)

    total = 0
    for prod in cart.products.all():
        if prod.quantity > 0:
            total += prod.price
        else:
            cart.products.remove(prod)
    
    cart.save()

    context = {
        'categories': categories,
        'total': total,
        'cart': cart.products.all()
    }

    return render(request, 'cart/show.html', context)

@login_required
def add(request, id):
    if request.method == 'GET':
        cart = Cart.objects.get(owner=request.user)
        product = Product.objects.get(pk=id)
        if product.quantity > 0:
            cart.products.add(product)
            cart.save()

            return redirect('cart:show')

@login_required
def delete(request):
    if request.method == 'GET':
        id = request.GET.get('prodId')
        product = Product.objects.get(pk=id)
        cart = Cart.objects.get(owner=request.user)
        cart.products.remove(product)
        cart.save()

        new_total = 0
        for prod in cart.products.all():
            new_total += prod.price

        return JsonResponse({
            'removedId': id,
            'newTotal': new_total
        })

cart/templates/cart/show.html
{% extends "base/index.html" %}
{% load static %}
{% load humanize %}
{% load l10n %}

{% block dynamic_messages %}
    <div id="dynamic_messages"></div>
{% endblock dynamic_messages %}

{% block breadcrumb %}{% endblock breadcrumb %}

{% block main %}
    <div id="cart-content" class="container my-lg-5">

    {% if cart %}
        <h1 class="display-5 mb-5">Produtos no carrinho</h1>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">Nome do anúncio</th>
                    <th scope="col">Descrição</th>
                    <th scope="col">Preço</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody id='tbody-products'>
                {% for prod in cart %}
                    <tr data-id="{{ prod.id }}">
                        <td>
                            <a href="{% url 'product:product_by_id' prod.id %}">
                                {{ prod.name }}
                            </a>
                        </td>
                        <td>{{ prod.small_description }}</td>
                        <td data-price={{ prod.price|unlocalize }}>R$ {{ prod.price|intcomma }}</td>
                        <td>
                            <button class="btn btn-danger" onclick="handleDelete('{{ prod.id }}');">Remover</button>
                        </td>
                    </tr>
                {% endfor %}

                <tr>
                    <td colspan="2"><strong>Total:</strong></td>
                    <td id="total-price" data-price={{ total|unlocalize }}><strong>R$ {{ total|intcomma }}</strong></td>
                </tr>
            </tbody>
        </table>

        <button type="button" class="btn btn-primary" onclick="handleCloseCart();">Finalizar compra</button>

    {% else %}
        <h1 class="display-5 mb-5">Seu carrinho está vazio :(</h1>
    {% endif %}
    </div>

    <div class="modal fade" tabindex="-1" id="remove-confirmation">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Tem certeza que deseja remover esse produto?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger">Sim, remover!</button>
            </div>
            </div>
        </div>
    </div>
{% endblock main %}

{% block pscript %}
function handleCloseCart() {
    productIds = [];
    $('#tbody-products').children().each((_, value) => {
        productIds.push($(value).data('id'))
    });

    $.ajax({
        headers: {
            'X-CSRFToken': '{{ csrf_token }}'
        },
        url: '{%url 'payment:close_cart' %}',
        type: 'POST',
        data: {
            productIds
        },
        success: (res) => {
            window.location = res.url
        },
    });
}

function handleDelete(prodId) {
    let removedId = null;

    $('#remove-confirmation').modal('show');
    $('#remove-confirmation').one('click', '.btn-danger', () => {
        $.ajax({
            url: '{%url 'cart:delete' %}',
            type: 'GET',
            data: {
                prodId
            },
            success: (res) => {
                removedId = res.removedId;

                $('#total-price').data('price', res.newTotal);
                $('#total-price').html(
                    `<strong>R$ ${res.newTotal.toLocaleString('pt-br', {minimumFractionDigits: 2})}</strong>`
                );

                $(`[data-id='${removedId}']`).remove();

                $('#remove-confirmation').modal('hide');

                const alert = `
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        Produto removido do carrinho.
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                `;
                $('#dynamic_messages').html(alert);

                if ($('#tbody-products').children().length - 1 === 0) {
                    const newContent = `
                        <h1 class="display-5 mb-5">Seu carrinho está vazio :(</h1>
                    `;

                    $('#cart-content').html(newContent);
                }
            },
        });
    });
}
{% endblock pscript %}

{% block pagination %}{% endblock pagination %}