cart/urls.py
from django.urls import path
from cart import views


app_name = 'cart'

urlpatterns = [
    path('', views.show, name='show'),
    path('add/<uuid:id>', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
]

fleamarket/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from fleamarket import views, settings

urlpatterns = [
    path('', views.index, name='index'),
    path('', include('users.urls')),
    path('product/', include('product.urls')),
    path('category/', include('category.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from product import views


app_name = 'product'

urlpatterns = [
    path('<uuid:id>/', views.product_by_id, name='product_by_id'),
    path('create/', views.create, name='create'),
    path('edit/<uuid:id>', views.edit, name='edit'),
    path('list/', views.list_by_user, name='list_by_user'),
    path('list_by_name/', views.list_by_name, name='list_by_name'),
    path('delete/', views.delete, name='delete'),
    path('fast_create/', views.fast_create, name='fast_create'),
    path('update_quantity/', views.update_quantity, name='update_quantity'),
    path('create_question/<uuid:id>', views.create_question, name='create_question'),
    path('answer_question/<uuid:id>', views.answer_question, name='answer_question'),
]

users/urls.py
from django.urls import path
from users import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

templates/base/footer.html
<footer class="text-center bg-dark">
    <div class="container py-2">
        <section>
            <a
            class="btn btn-link btn-floating btn-lg m-1 text-light"
            href="#!"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="fab fa-facebook-f"></i
            ></a>

            <a
            class="btn btn-link btn-floating btn-lg m-1 text-light"
            href="#!"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="fab fa-twitter"></i
            ></a>

            <a
            class="btn btn-link btn-floating btn-lg m-1 text-light"
            href="#!"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="fab fa-instagram"></i
            ></a>
        </section>
    </div>

    <div class="text-center text-light p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2021 Copyright:
        <a class="text-light" href="#">Flea Market</a>
    </div>
</footer>

templates/base/index.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">

        <title>
            {% block title %}
                Flea Market
            {% endblock title %}
        </title>

        <style>
            {% block pstyle %}{% endblock pstyle %}
        </style>
    </head>

    <body>
    {% block dynamic_messages %}{% endblock dynamic_messages %}
    {% block messages %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
    {% endblock messages %}

    <div class="footer-wrapper">
        {% include './nav.html' %}

        {% block breadcrumb %}
            <div class="container my-3">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">Início</li>
                </ol>
            </nav>
            </div>
        {% endblock breadcrumb %}

        <main>
            {% block main %}{% endblock main %}
            {% block pagination %}{% endblock pagination %}
        </main>
    </div>
    {% include './footer.html' %}

    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>

    <script>
        {% block pscript %}{% endblock pscript %}
    </script>

    </body>
</html>

templates/base/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">Flea Market</a>
    <button class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.view_name == 'index' %}active{% endif %}"
                    href="{% url 'index' %}">
                Página principal <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle {% if request.resolver_match.view_name == 'category:products_by_category' %}active{% endif %}"
                    href="#"
                    id="navbarScrollingDropdown"
                    role="button"
                    data-toggle="dropdown"
                    aria-expanded="false">
                    Categorias
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                {% if categories %}
                    {% for cat in categories %}
                        <li>
                            <a class="dropdown-item" href="{% url 'category:products_by_category' cat.slug %}">
                                {{ cat.name }}
                            </a>
                        </li>
                    {% endfor %}
                {% else %}
                        <span class="dropdown-item-text">Sem categorias</span>
                {% endif %}
                </ul>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="#"></a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.view_name == 'product:create' %}active{% endif %}"
                        href="{% url 'product:create' %}">
                        Criar anúncio
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.view_name == 'product:list_by_user' %}active{% endif %}"
                        href="{% url 'product:list_by_user' %}">
                        Seus anúncios
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.view_name == 'payment:purchase_show' %}active{% endif %}"
                        href="{% url 'payment:purchase_show' %}">
                        Suas compras
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.view_name == 'payment:sale_show' %}active{% endif %}"
                        href="{% url 'payment:sale_show' %}">
                        Suas vendas
                    </a>
                </li>
            {% endif %}
        </ul>

        {% if user.is_authenticated %}
            <ul class="navbar-nav mx-4">
                <li class="nav-item">
                    <span class="navbar-text">
                        Olá, {{ user.first_name }}!
                    </span>
                </li>
                <li class="nav-item">
                    <a
                    class="ml-4 btn btn-outline-success mr-3 {% if request.resolver_match.view_name == 'cart:show' %}active{% endif %}"
                    href="{% url 'cart:show' %}">
                        <i class="fas fa-shopping-cart"></i>
                    </a>
                </li>
            </ul>
        {% endif %}

        <form method="POST" action="{% url 'product:list_by_name' %}" class="form-inline my-2 my-lg-0">
            {% csrf_token %}
            <input class="form-control mr-sm-2"
                    type="search"
                    name="name"
                    placeholder="Encontre produtos!"
                    aria-label="Search"/>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                <i class="fas fa-search"></i>
            </button>
        </form>

        <ul class="navbar-nav mx-4">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="btn btn-outline-success mr-3" href="{% url 'users:logout' %}">
                        Sair
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a
                    class="btn btn-outline-success mr-3 {% if request.resolver_match.view_name == 'users:login' %}active{% endif %}"
                    href="{% url 'users:login' %}">
                        Entrar
                    </a>
                </li>
                <a class="nav-link {% if request.resolver_match.view_name == 'users:signup' %}active{% endif %}"
                    <a class="nav-link" href="{% url 'users:signup' %}">Cadastre-se</a>
                </li>
            {% endif %}
        </ul>

    </div>
</nav>