cart/urls.py
from django.urls import path
from cart import views


app_name = 'cart'

urlpatterns = [
    path('', views.show, name='show'),
    path('add/<uuid:id>', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
]

fleamarket/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from fleamarket import views, settings

urlpatterns = [
    path('', views.index, name='index'),
    path('', include('users.urls')),
    path('product/', include('product.urls')),
    path('category/', include('category.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from payment import views


app_name = 'payment'

urlpatterns = [
    path('purchase/', views.purchase_show, name='purchase_show'),
    path('sale/', views.sale_show, name='sale_show'),
    path('buy/<uuid:id>', views.buy, name='buy'),
    path('close_cart/', views.close_cart, name='close_cart'),
]

product/urls.py
from django.urls import path
from product import views


app_name = 'product'

urlpatterns = [
    path('<uuid:id>/', views.product_by_id, name='product_by_id'),
    path('create/', views.create, name='create'),
    path('edit/<uuid:id>', views.edit, name='edit'),
    path('list/', views.list_by_user, name='list_by_user'),
    path('list_by_name/', views.list_by_name, name='list_by_name'),
    path('delete/', views.delete, name='delete'),
    path('fast_create/', views.fast_create, name='fast_create'),
    path('update_quantity/', views.update_quantity, name='update_quantity'),
    path('create_question/<uuid:id>', views.create_question, name='create_question'),
    path('answer_question/<uuid:id>', views.answer_question, name='answer_question'),
]

product/models.py
import uuid
from django.db import models
from category.models import Category
from users.models import User


class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=12, decimal_places=2, default=1)
    small_description = models.TextField(blank=True)
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=100)
    image = models.ImageField(upload_to='images/')
    quantity = models.IntegerField(default=1)
    available = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Question(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    text = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

class Answer(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    text = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.OneToOneField(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

product/forms.py
from django.forms import ModelForm, TextInput
from django.core.exceptions import ValidationError
from product.models import Product

class ProductForm(ModelForm):
    
    class Meta:
        model = Product
        fields = ['name', 'price', 'small_description', 'description', 'image', 'quantity', 'category']
        localized_fields = ['price']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].error_messages={'required': 'Campo obrigatório.'}
        self.fields['name'].widget.attrs.update({'class': 'form-control form-control-sm'})
        
        self.fields['small_description'].error_messages={'required': 'Campo obrigatório'}
        self.fields['small_description'].widget = TextInput()
        self.fields['small_description'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['description'].error_messages={'required': 'Campo obrigatório'}
        self.fields['description'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['category'].error_messages={'required': 'Campo obrigatório'}
        self.fields['category'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['price'].min_value=1
        self.fields['price'].error_messages={'required': 'Campo obrigatório.',
                                             'invalid': 'Valor inválido.',
                                             'max_digits': 'Mais de 5 dígitos no total.',
                                             'max_decimal_places': 'Mais de 2 dígitos decimais.',
                                             'max_whole_digits': 'Mais de 3 dígitos inteiros.',
                                             'min_value': 'Um produto tem que custar pelo menos um real.'}
        self.fields['price'].widget.attrs.update({
            'class': 'form-control form-control-sm',
            'onkeypress': 'return (event.charCode >= 48 && event.charCode <= 57) || event.charCode == 44'
        })

        self.fields['quantity'].min_value=1
        self.fields['quantity'].error_messages={
            'required': 'Campo obrigatório',
            'min_value': 'A quantidade deve ser maior ou igual a zero.'
        }
        self.fields['quantity'].widget.attrs.update({
            'class': 'form-control form-control-sm',
        })

        self.fields['image'].error_messages={'required': 'Campo obrigatório',
                                              'invalid_image': 'Imagem inválida.'}
        self.fields['image'].widget.attrs.update({'class': 'btn btn-outline-secondary btn-sm'})


    def clean_price(self):
        data = self.cleaned_data['price']
        if float(data) <= 0:
            raise ValidationError(self.fields['price'].error_messages['min_value'])
        else:
            return data

    def clean_quantity(self):
        data = self.cleaned_data['quantity']
        if float(data) < 0:
            raise ValidationError(self.fields['quantity'].error_messages['min_value'])
        else:
            return data

product/views.py
from django.http.response import HttpResponseBadRequest, JsonResponse
from django.contrib.auth.decorators import login_required
from django.template.defaultfilters import slugify
from django.shortcuts import redirect, render, get_object_or_404
from django.core.paginator import Paginator
from django.contrib import messages
from product.models import Answer, Product, Question
from product.forms import ProductForm
from category.models import Category


def product_by_id(request, id):
    categories = Category.objects.all()

    product = get_object_or_404(Product, pk=id)

    questions = []
    questionsQuery = Question.objects.filter(product=id)
    if questionsQuery:
        for q in questionsQuery:
            question_awnser = []
            question_awnser.append(q)

            answer = Answer.objects.filter(question=q.id)
            if answer:
                question_awnser.append(answer[0])

            questions.append(question_awnser)

    context = {
        'categories': categories,
        'product': product,
        'questions': questions,
    }

    return render(request, 'product/product_by_id.html', context)

def list_by_name(request):
    categories = Category.objects.all()

    products = []
    if request.method == 'POST':
        name = request.POST.get('name')
        products = Product.objects.all().filter(name__contains=name, quantity__gt=0).order_by('-created_at')

    context = {
        'categories': categories,
        'products': products,
        'name': name
    }

    return render(request, 'product/list_by_name.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.slug = slugify(product.name)
            product.owner = request.user
            product.save()

            messages.success(request, 'Produto criado com sucesso.')
            return redirect('product:product_by_id', id=product.id)
        else:
            messages.error(request, form.errors)
    else:
        form = ProductForm()

    categories = Category.objects.all()
    context = {
        'categories': categories,
        'form': form
    }

    return render(request, 'product/create.html', context)

@login_required
def edit(request, id):
    product = get_object_or_404(Product, pk=id)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            product = form.save(commit=False)
            product.slug = slugify(product.name)
            product.owner = request.user
            product.save()

            messages.success(request, 'Produto atualizado com sucesso.')
            return redirect('product:product_by_id', id=product.id)
        else:
            messages.error(request, form.errors)
    else:
        form = ProductForm(instance=product)

    categories = Category.objects.all()
    context = {
        'product_id': id,
        'categories': categories,
        'form': form
    }

    return render(request, 'product/edit.html', context)

@login_required
def delete(request):
    if request.method == 'GET':
        id = request.GET.get('prodId')
        product = Product.objects.get(pk=id)

        price = product.price
        quantity = product.quantity

        product.image.delete()
        product.delete()
        return JsonResponse({
            'removedId': id,
            'price': price,
            'quantity': quantity
        })

@login_required
def list_by_user(request):
    categories = Category.objects.all().order_by('name')

    form = ProductForm()

    page = request.GET.get('page')
    products = Product.objects.all().filter(owner_id=request.user.id).order_by('-created_at')
    paginator = Paginator(products, 6)
    prod_obj = paginator.get_page(page)

    total_per_page = 0
    for prod in prod_obj:
        questions_count = Question.objects.filter(product=prod.id, answer__isnull=True).count()
        prod.notification = questions_count

        total_per_page += (prod.price * prod.quantity)

    context = {
        'categories': categories,
        'products': prod_obj,
        'form': form,
        'total_per_page': total_per_page
    }

    return render(request, 'product/list_by_user.html', context)

@login_required
def fast_create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.slug = slugify(product.name)
            product.owner = request.user
            product.save()

            res = {
                'id': product.id,
                'price': product.price,
                'quantity': product.quantity,
                'small_description': product.small_description,
                'name': product.name,
            }

            return JsonResponse(res, safe=False)
        else:
            return HttpResponseBadRequest(form.errors.as_json(), content_type="application/json")

@login_required
def update_quantity(request):
    if request.method == 'POST':
        id = request.POST.get('prodId')
        quantity = request.POST.get('quantity')
        # limit = int(request.POST.get('limit'))

        product = Product.objects.get(pk=id)
        product.quantity = quantity
        product.save()

        # total_price = Product.objects.all().filter(owner_id=request.user.id).order_by('-created_at')[:limit].aggregate(sum=Sum(F('price') * F('quantity')))

        return JsonResponse({
            # 'total_price': float(total_price['sum'])
        })

@login_required
def create_question(request, id):
    product = get_object_or_404(Product, pk=id)

    if request.method == 'POST':
        if (request.user == product.owner):
            messages.error(request, 'Não é possível fazer perguntas no próprio anúncio.')
        else:
            question = request.POST.get('question')
            if question == '':
                return redirect('product:product_by_id', id=id)
            
            new_question = Question(text=question, owner=request.user, product=product)
            new_question.save()
            messages.success(request, 'Pergunta criada com sucesso.')
            

    return redirect('product:product_by_id', id=id)

@login_required
def answer_question(request, id):
    question = get_object_or_404(Question, pk=id)

    if request.method == 'POST':
        if (request.user == question.owner):
            messages.error(request, 'Não é possível responder a própria pergunta.')
        else:
            answer = request.POST.get('answer')
            if answer == '':
                return redirect('product:product_by_id', id=question.product.id)
            
            new_answer = Answer(text=answer, owner=request.user, question=question)
            new_answer.save()
            messages.success(request, 'Pergunta respondida com sucesso.')
            

    return redirect('product:product_by_id', id=question.product.id)

product/templates/product/create.html
{% extends 'base/index.html' %}
{% load static %}

{% block breadcrumb %}{% endblock breadcrumb %}

{% block main %}
    <div class="container my-lg-5 form-box">

    <h1 class="display-5">Crie seu anúncio</h1>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}">Nome do produto</label>
            {{ form.name }}
        </div>
        <div class="form-group">
            <label for="{{ form.small_description.id_for_label }}">Descreva em poucas palavras</label>
            {{ form.small_description }}
        </div>
        <div class="form-group">
            <label for="{{ form.price.id_for_label }}">Preço</label>
            {{ form.price }}
        </div>
        <div class="form-group">
            <label for="{{ form.quantity.id_for_label }}">Quantidade</label>
            {{ form.quantity }}
        </div>
        <div class="form-group">
            <label for="{{ form.image.id_for_label }}">Foto do produto</label>
            {{ form.image }}
        </div>
        <div class="form-group">
            <label for="{{ form.description.id_for_label }}">Descrição</label>
            {{ form.description }}
        </div>
        <div class="form-group">
            <label for="{{ form.category.id_for_label }}">Categoria</label>
            {{ form.category }}
        </div>
        <button type="submit" class="btn btn-primary">Criar anúncio</button>
    </form>

    </div>
{% endblock main %}

{% block pagination %}{% endblock pagination %}

product/templates/product/edit.html
{% extends 'base/index.html' %}
{% load static %}

{% block breadcrumb %}{% endblock breadcrumb %}

{% block main %}
    <div class="container my-lg-5 form-box">

    <h1 class="display-5">Editando seu anúncio</h1>

    <form action="{%url 'product:edit' product_id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}">Nome do produto</label>
            {{ form.name }}
        </div>
        <div class="form-group">
            <label for="{{ form.small_description.id_for_label }}">Descreva em poucas palavras</label>
            {{ form.small_description }}
        </div>
        <div class="form-group">
            <label for="{{ form.price.id_for_label }}">Preço</label>
            {{ form.price }}
        </div>
        <div class="form-group">
            <label for="{{ form.quantity.id_for_label }}">Quantidade</label>
            {{ form.quantity }}
        </div>
        <div class="form-group">
            <label for="{{ form.image.id_for_label }}">Foto do produto</label>
            {{ form.image }}
        </div>
        <div class="form-group">
            <label for="{{ form.description.id_for_label }}">Descrição</label>
            {{ form.description }}
        </div>
        <div class="form-group">
            <label for="{{ form.category.id_for_label }}">Categoria</label>
            {{ form.category }}
        </div>
        <button type="submit" class="btn btn-primary">Atualizar</button>
    </form>

    </div>
{% endblock main %}

{% block pagination %}{% endblock pagination %}

product/templates/product/list_by_user.html
{% extends "base/index.html" %}
{% load static %}
{% load humanize %}
{% load l10n %}

{% block pstyle %}
    .ptab:hover {
        text-decoration: underline;
    }

    #arrow {
        font-size: 20px;
        margin-left: 10px;
    }
{% endblock pstyle %}

{% block dynamic_messages %}
    <div id="dynamic_messages"></div>
{% endblock dynamic_messages %}

{% block breadcrumb %}{% endblock breadcrumb %}

{% block main %}
    <div class="container my-lg-5">

    <h1 class="display-5 mb-3 ptab" data-toggle="collapse" href="#fast-creation-collapse" role="button" aria-expanded="false" aria-controls="collapseExample">
        Criação rápida
        <span id="arrow"><i class="fas fa-chevron-down"></i></span>
    </h1>
    <div class="collapse form-box" id="fast-creation-collapse" style="align-items: flex-start;">
        <form method="POST" enctype="multipart/form-data" class="mb-5" onsubmit="handleFastCreate(this, event);">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.name.id_for_label }}">Nome do produto</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label for="{{ form.small_description.id_for_label }}">Descreva em poucas palavras</label>
                {{ form.small_description }}
            </div>
            <div class="form-group">
                <label for="{{ form.price.id_for_label }}">Preço</label>
                {{ form.price }}
            </div>
            <div class="form-group">
                <label for="{{ form.quantity.id_for_label }}">Quantidade</label>
                {{ form.quantity }}
            </div>
            <div class="form-group">
                <label for="{{ form.image.id_for_label }}">Foto do produto</label>
                {{ form.image }}
            </div>
            <div class="form-group">
                <label for="{{ form.description.id_for_label }}">Descrição</label>
                {{ form.description }}
            </div>
            <div class="form-group">
                <label for="{{ form.category.id_for_label }}">Categoria</label>
                {{ form.category }}
            </div>
            <button type="submit" class="btn btn-primary">Criar anúncio</button>
        </form>
    </div>

    <h1 class="display-5 mb-5">Seus produtos a venda</h1>

    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col">Nome do anúncio</th>
                <th scope="col">Descrição</th>
                <th scope="col">Quantidade</th>
                <th scope="col">Preço</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody id='tbody-products'>
            {% for prod in products %}
                <tr data-id="{{ prod.id }}">
                    <td>
                    <a href="{% url 'product:product_by_id' prod.id %}">
                        {% if prod.notification > 0 %}
                            <span class="mr-3 badge badge-primary">{{ prod.notification }}</span>
                        {% endif %}
                        {{ prod.name }}
                    </a>
                    </td>
                    <td>{{ prod.small_description }}</td>
                    <td>
                        <form>
                            {% csrf_token %}
                            <input
                                type="text"
                                class="form-control"
                                value="{{ prod.quantity }}"
                                onblur="handleUpdateQuantity('{{prod.id}}', this.value, event)"/>
                        </form>
                    </td>
                    <td data-price={{ prod.price|unlocalize }}>R$ {{ prod.price|intcomma }}</td>
                    <td>
                        <a class="btn btn-primary" href="{%url 'product:edit' prod.id %}">Editar</a>
                        <button class="btn btn-danger" onclick="handleDelete('{{ prod.id }}');">Remover</button>
                    </td>
                </tr>
            {% endfor %}

            <tr>
                <td colspan="3"><strong>Lucro estimado:</strong></td>
                <td id="total-price" data-price={{ total_per_page|unlocalize }}><strong>R$ {{ total_per_page|intcomma }}</strong></td>
            </tr>
        </tbody>
    </table>

    </div>

    <div class="modal fade" tabindex="-1" id="remove-confirmation">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Tem certeza que deseja remover esse produto?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-danger">Sim, remover!</button>
            </div>
            </div>
        </div>
    </div>
{% endblock main %}

{% block pscript %}
$(() => {
    $('#fast-creation-collapse').on('shown.bs.collapse', () => {
        $('#arrow > i').attr('class', 'fas fa-chevron-up');
    });

    $('#fast-creation-collapse').on('hidden.bs.collapse', () => {
        $('#arrow > i').attr('class', 'fas fa-chevron-down');
    });
});

function handleFastCreate(form, e) {
    e.preventDefault();
    const data = new FormData(form);
    $.ajax({
        url: '{%url 'product:fast_create' %}',
        type: 'POST',
        data,
        processData: false,
        contentType: false,
        success: (res) => {
            const formattedPrice = parseFloat(res.price).toLocaleString('pt-br', {minimumFractionDigits: 2});
            const tr = `
                <tr data-id="${res.id}">
                    <td>${res.name}</td>
                    <td>${res.small_description}</td>
                    <td>
                        <form>
                            {% csrf_token %}
                            <input
                                type="text"
                                class="form-control"
                                value="${res.quantity}"
                                onblur="handleUpdateQuantity('${res.id}', this.value, event)"/>
                        </form>
                    </td>
                    <td data-price=${parseFloat(res.price)}>R$ ${formattedPrice}</td>
                    <td>
                        <a class="btn btn-primary" href="/product/edit/${res.id}">Editar</a>
                        <button class="btn btn-danger" onclick="handleDelete('${res.id}');">Remover</button>
                    </td>
                </tr>
            `;
            $('#tbody-products').prepend(tr);

            const totalPrice = parseFloat($('#total-price').data('price'));
            const newTotalPrice = totalPrice + parseFloat(res.price) * parseFloat(res.quantity);
            $('#total-price').data('price', newTotalPrice);
            $('#total-price').html(
                `<strong>R$ ${newTotalPrice.toLocaleString('pt-br', {minimumFractionDigits: 2})}</strong>`
            );

            const alert = `
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    Anúncio criado com sucesso.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            `;
            $('#dynamic_messages').html(alert);
        },
        error: (res) => {
            let message = '';
            const errors = res.responseJSON;
            for (const error in errors) {
                for (const msg of errors[error]) {
                    message += `${msg['message']}<br>`;
                }
            }
            const alert = `
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    ${message}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            `;
            $('#dynamic_messages').html(alert);
        },
    });
}

function handleUpdateQuantity(prodId, quantity, e) {
    e.preventDefault();

    if (quantity < 0) {
        const alert = `
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                A quantidade não pode ser menor que zero.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        `;
        $('#dynamic_messages').html(alert);
        return
    }

    $.ajax({
        url: '{%url 'product:update_quantity' %}',
        headers: {
            'X-CSRFToken': '{{ csrf_token }}'
        },
        type: 'POST',
        data: {
            prodId,
            quantity,
        },
        success: (res) => {
            let totalPrice = 0;
            $('#tbody-products').children().each((_, value) => {
                const quantity = $(value).find('input[type=text]').val();
                const price = $(value).find('td').eq(3).data('price');
                if (quantity && price) {
                    totalPrice += quantity * price;
                }
            });
            $('#total-price').data('price', totalPrice);
            $('#total-price').html(
                `<strong>R$ ${totalPrice.toLocaleString('pt-br', {minimumFractionDigits: 2})}</strong>`
            );

            const alert = `
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    Quantidade atualizada.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            `;
            $('#dynamic_messages').html(alert);
        },
    });
}

function handleDelete(prodId) {
    let removedId = null;

    $('#remove-confirmation').modal('show');
    $('#remove-confirmation').one('click', '.btn-danger', () => {
        $.ajax({
            url: '{%url 'product:delete'%}',
            type: 'GET',
            data: {
                prodId
            },
            success: (res) => {
                removedId = res.removedId;

                const totalPrice = parseFloat($('#total-price').data('price'));
                const newTotalPrice = totalPrice - (parseFloat(res.price) * parseFloat(res.quantity));
                $('#total-price').data('price', newTotalPrice);
                $('#total-price').html(
                    `<strong>R$ ${newTotalPrice.toLocaleString('pt-br', {minimumFractionDigits: 2})}</strong>`
                );

                $(`[data-id='${removedId}']`).remove();

                $('#remove-confirmation').modal('hide');

                const alert = `
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        Produto removido.
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                `;
                $('#dynamic_messages').html(alert);
            },
        });
    });
}
{% endblock pscript %}

{% block pagination %}
    {% if products.has_other_pages %}
        <div class="container">
        <div class="row justify-content-center">
        <div class="col-auto">
            <nav>

            <ul class="pagination">
                {% if products.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ products.previous_page_number }}">
                            <i class="fas fa-caret-left"></i>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">
                            <i class="fas fa-caret-left"></i>
                        </a>
                    </li>
                {% endif %}

                {% for i in products.paginator.page_range %}
                    {% if products.number == i %}
                        <li class="page-item active"><a class="page-link" href="#">{{ i }} </a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if products.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ products.next_page_number }}">
                            <i class="fas fa-caret-right"></i>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">
                            <i class="fas fa-caret-right"></i>
                        </a>
                    </li>
                {% endif %}
            </ul>

            </nav>
        </div>
        </div>
        </div>
    {% endif %}
{% endblock pagination %}